Feat/b2c search/7
impostor-commerce/impostor-commerce-backend pull request #49
Opened 2024-12-10 10:30 UTC by bbobsang

- 제목 : [#7] feat: B2B 화면에서 주문 리스트 조회 기능 추가

## 🔘Part 
-B2B 화면에서 주문 리스트 조회

## 🔎 작업 내용 
- 최대한 상세히 작성

## 🔧 앞으로의 과제 
- 현재 해결 못한 부분이나 남은 과제 작성

## ➕ 이슈 링크 
- #이슈번호

2024-12-10 13:31 UTC, worldcenter96 approved these changes
코드가 깔끔하니 보기 좋아용!

2024-12-10 22:41 UTC, hwk9407 requested changes
전체적으로 컨벤션들 다 신경써서 잘 작성해주셨네요 고생 많으셨습니다ㅎㅎ

2024-12-10 22:41 UTC, hwk9407 commented on admin/src/main/java/com/sparta/admin/member/dto/request/B2CMemberSearchRequest.java
> +public class B2CMemberSearchRequest {
혹시 `B2CMemberSearchRequest` 어디서 쓰이고 있나요?

2024-12-10 22:41 UTC, hwk9407 commented on b2c/src/main/java/com/sparta/b2c/B2cApplication.java
> +@SpringBootApplication(scanBasePackages = "com.sparta.impostor", exclude = { SecurityAutoConfiguration.class })
"com.sparta" 로 변경해주시면 감사합니다! common이나 다른 모듈이 "com.sparta" 까지만 적혀있을거라 범위가 나중에 문제가 될거같아서요

2024-12-10 23:41 UTC, gabeen-dev approved these changes

2024-12-10 23:41 UTC, gabeen-dev commented on admin/src/main/java/com/sparta/admin/member/service/B2CSearchService.java
> +
status에 따라 조회 되는 조건절을 주셨군요...!👍 저도 전체 조회기능을 수행해야 하는데 참고 하겠습니다!

2024-12-11 00:27 UTC, matino0216 approved these changes
동료들도 읽기 쉽도록 깔끔하게 작성해주셨네요! 금방 이해할 수 있었습니다. 고생하셨습니다!

2024-12-11 00:41 UTC, bbobsang commented on admin/src/main/java/com/sparta/admin/member/dto/request/B2CMemberSearchRequest.java
> +public class B2CMemberSearchRequest {
Request 주입했습니당

2024-12-11 00:42 UTC, bbobsang commented on b2c/src/main/java/com/sparta/b2c/B2cApplication.java
> +@SpringBootApplication(scanBasePackages = "com.sparta.impostor", exclude = { SecurityAutoConfiguration.class })
수정 완료했습니다!

2024-12-11 00:46 UTC, hwk9407 approved these changes

2024-12-11 00:48 UTC, merged